name: Terraform Secure Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  terraform:
    name: Secure Terraform Deployment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Run Checkov Scan
      uses: bridgecrewio/checkov-action@v2
      with:
        skip_download: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
